# Generated by Django 5.2.5 on 2025-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehub', '0003_ingredient_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
    ]
