# Generated by Django 5.2.5 on 2025-09-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehub', '0004_remove_profile_role_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coffeehub.profile', verbose_name='Пользователь'),
        ),
    ]
