# Generated by Django 5.2.5 on 2025-09-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehub', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='picture',
            field=models.ImageField(null=True, upload_to='ingredients', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
